In [1]:
import tensorflow as tf
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]).astype('float32')
a = a.reshape(-1,3,3,1)

In [5]:
a.shape

(1, 3, 3, 1)

In [8]:
pads = np.array([[1,1],[2,2]])
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Input(shape = a.shape[1:]))
model.add(tf.keras.layers.ZeroPadding2D(padding = pads))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
zero_padding2d_1 (ZeroPaddin (None, 5, 7, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [9]:
output = model(a)

In [10]:
output

<tf.Tensor: shape=(1, 5, 7, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [2.],
         [3.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [4.],
         [5.],
         [6.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [7.],
         [8.],
         [9.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [11]:
import tensorflow as tf
import numpy as np

In [12]:
A = np.array([[1,2,3,4,5],[4,3,2,1,0],[5,6,7,8,9],[4,3,2,1,0],[0,1,2,3,4]]).astype('float32')
A = A.reshape(-1,5,5,1)

In [14]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Input(shape = (5,5,1)))
model.add(tf.keras.layers.MaxPool2D())
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
max_pooling2d (MaxPooling2D) (None, 2, 2, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [15]:
B = model.predict(A)

In [16]:
B

array([[[[4.],
         [4.]],

        [[6.],
         [8.]]]], dtype=float32)

In [20]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import cifar10
import matplotlib.pyplot as plt

In [21]:
(x_train, y_train),(x_test, y_test) = cifar10.load_data()
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train / 255.0
x_test = x_test / 255.0

In [28]:
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [30]:
x_train.shape

(50000, 32, 32, 3)

In [32]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Input(shape = x_train.shape[1:]))
model.add(tf.keras.layers.MaxPool2D())
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 3)         0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [33]:
output = model.predict(x_train[:8])

In [38]:
output

array([[[[0.23137255, 0.24313726, 0.24705882],
         [0.26666668, 0.21176471, 0.16862746],
         [0.47058824, 0.35686275, 0.24705882],
         ...,
         [0.65882355, 0.53333336, 0.42352942],
         [0.61960787, 0.5176471 , 0.42352942],
         [0.59607846, 0.49019608, 0.40392157]],

        [[0.14901961, 0.09803922, 0.08235294],
         [0.41568628, 0.24705882, 0.10980392],
         [0.5058824 , 0.36078432, 0.21176471],
         ...,
         [0.5568628 , 0.4117647 , 0.26666668],
         [0.50980395, 0.36862746, 0.22745098],
         [0.4745098 , 0.33333334, 0.19607843]],

        [[0.32941177, 0.20784314, 0.11372549],
         [0.5058824 , 0.32156864, 0.15294118],
         [0.53333336, 0.34509805, 0.1764706 ],
         ...,
         [0.4745098 , 0.3137255 , 0.1764706 ],
         [0.40392157, 0.2627451 , 0.1254902 ],
         [0.29411766, 0.18431373, 0.09803922]],

        ...,

        [[0.84705883, 0.68235296, 0.34117648],
         [0.65882355, 0.47843137, 0.13725491]

In [40]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
import numpy as np
import matplotlib.pyplot as plt

In [53]:
(x_train, y_train),(x_test, y_test) = cifar10.load_data()

In [54]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

In [58]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape = x_train.shape[1:]))
model.add(tf.keras.layers.Conv2D(filters = 1,kernel_size = (3,3), padding = 'same', strides = (1,1)))
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 32, 32, 1)         28        
Total params: 28
Trainable params: 28
Non-trainable params: 0
_________________________________________________________________


In [55]:
x_train.shape

(50000, 32, 32, 3)

In [62]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.layers import Input, Dense, Conv2D, MaxPool2D, BatchNormalization, Dropout, Flatten
from tensorflow.keras.optimizers import RMSprop

In [83]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train / 255.0
x_test = x_test / 255.0
x_train = x_train.reshape(-1,28,28,1)
x_test = x_test.reshape(-1,28,28,1)

y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [85]:
model = tf.keras.models.Sequential()
model.add(Input(shape = (28,28,1)))
model.add(Conv2D(filters=16,kernel_size = (3,3),activation = 'relu'))
model.add(BatchNormalization())
model.add(MaxPool2D())

model.add(Conv2D(filters=32,kernel_size = (3,3), activation = 'relu'))
model.add(MaxPool2D())
model.add(Dropout(rate = 0.2))

model.add(Flatten())
model.add(Dense(units =10,activation = 'softmax'))
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 26, 26, 16)        160       
_________________________________________________________________
batch_normalization_1 (Batch (None, 26, 26, 16)        64        
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 13, 13, 16)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 11, 11, 32)        4640      
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 5, 5, 32)          0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 5, 5, 32)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 800)             

In [88]:
model.compile(optimizer=RMSprop(learning_rate=0.01),loss = 'categorical_crossentropy',metrics=['accuracy'])

import os
path = './log/20210926_2/'
if not os.path.isdir(path):
    os.mkdir(path)
callback = TensorBoard(log_dir = path)

In [93]:
model.fit(x_train, y_train, epochs=100, batch_size = 200, callbacks=[callback], validation_split=0.2, verbose = 0)

In [94]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Conv2D, MaxPool2D, BatchNormalization, Dropout, Flatten, Dense
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.callbacks import TensorBoard

In [95]:
(x_train, y_train),(x_test, y_test) = tf.keras.datasets.cifar100.load_data()

169009152/169001437 [==============================] - 37s 0us/step


In [97]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train /255.0
x_test = x_test / 255.0

In [99]:
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [106]:
model = Sequential()
model.add(Input(shape = x_train.shape[1:]))
model.add(Conv2D(filters = 16, kernel_size = (3,3), padding = 'same',activation = 'relu'))
model.add(BatchNormalization())
model.add(MaxPool2D())

model.add(Conv2D(filters=32, kernel_size = (3,3), padding = 'same',activation = 'relu'))
model.add(BatchNormalization())
model.add(MaxPool2D())
model.add(Dropout(rate = 0.25))

model.add(Conv2D(filters=64, kernel_size = (3,3), padding = 'same',activation = 'relu'))
model.add(BatchNormalization())
model.add(MaxPool2D())
model.add(Dropout(rate = 0.5))

model.add(Flatten())
model.add(Dense(units=100, activation = 'softmax'))

model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           (None, 32, 32, 16)        448       
_________________________________________________________________
batch_normalization_4 (Batch (None, 32, 32, 16)        64        
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 16, 16, 16)        0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 16, 16, 32)        4640      
_________________________________________________________________
batch_normalization_5 (Batch (None, 16, 16, 32)        128       
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 8, 8, 32)          0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 8, 8, 32)        

In [111]:
model.compile(optimizer=RMSprop(), loss = 'categorical_crossentropy', metrics = ['accuracy'])
os.mkdir('./log/20210926_4/')
callback_1 = TensorBoard(log_dir = './log/20210926_4/')
model.fit(x_train, y_train, validation_split=0.2, epochs = 100, batch_size = 200, callbacks=[callback_1],verbose=2)

Epoch 1/100
200/200 - 4s - loss: 2.6056 - accuracy: 0.3582 - val_loss: 2.3103 - val_accuracy: 0.4162
Epoch 2/100
200/200 - 2s - loss: 2.3522 - accuracy: 0.4011 - val_loss: 2.3185 - val_accuracy: 0.4099
Epoch 3/100
200/200 - 2s - loss: 2.2803 - accuracy: 0.4154 - val_loss: 2.2058 - val_accuracy: 0.4357
Epoch 4/100
200/200 - 2s - loss: 2.2166 - accuracy: 0.4286 - val_loss: 2.2180 - val_accuracy: 0.4268
Epoch 5/100
200/200 - 2s - loss: 2.1913 - accuracy: 0.4326 - val_loss: 2.2034 - val_accuracy: 0.4355
Epoch 6/100
200/200 - 2s - loss: 2.1574 - accuracy: 0.4424 - val_loss: 2.2582 - val_accuracy: 0.4205
Epoch 7/100
200/200 - 2s - loss: 2.1497 - accuracy: 0.4426 - val_loss: 2.1723 - val_accuracy: 0.4414
Epoch 8/100
200/200 - 2s - loss: 2.1244 - accuracy: 0.4445 - val_loss: 2.3701 - val_accuracy: 0.3993
Epoch 9/100
200/200 - 2s - loss: 2.1166 - accuracy: 0.4478 - val_loss: 2.1670 - val_accuracy: 0.4407
Epoch 10/100
200/200 - 2s - loss: 2.0880 - accuracy: 0.4516 - val_loss: 2.1490 - val_accura