In [1]:
from tensorflow.keras.layers import Permute, Reshape

In [2]:
import numpy as np
import tensorflow as tf

In [4]:
A = np.array([[1,2,3,4],[5,7,8,9]], dtype = 'float32')
A = A.reshape(1,2,4,1)
# 1, 2, 4, 1 에서 1:배치사이즈, 2:row 크기, 3:cols, 4:channels 

In [30]:
x = tf.keras.layers.Input(shape=(2,4,1))
# reshape 해준다.
y = tf.keras.layers.Reshape([4,2,1])(x)

# 차원의 축을 변경한다.
z = tf.keras.layers.Permute([2,1,3])(x)

# 각 데이터를 (2,2)로 늘려준다.
k = tf.keras.layers.UpSampling2D()(x)

model = tf.keras.Model(inputs = x, outputs = [y,z,k])
model.summary()

Model: "model_6"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_9 (InputLayer)            [(None, 2, 4, 1)]    0                                            
__________________________________________________________________________________________________
reshape_8 (Reshape)             (None, 4, 2, 1)      0           input_9[0][0]                    
__________________________________________________________________________________________________
permute_8 (Permute)             (None, 4, 2, 1)      0           input_9[0][0]                    
__________________________________________________________________________________________________
up_sampling2d_3 (UpSampling2D)  (None, 4, 8, 1)      0           input_9[0][0]                    
Total params: 0
Trainable params: 0
Non-trainable params: 0
________________________________

In [31]:
output = model.predict(A)
output[0][0,:,:,0]

array([[1., 2.],
       [3., 4.],
       [5., 7.],
       [8., 9.]], dtype=float32)

In [32]:
output[1][0,:,:,0]

array([[1., 5.],
       [2., 7.],
       [3., 8.],
       [4., 9.]], dtype=float32)

In [33]:
output[2][0,:,:,0]

array([[1., 1., 2., 2., 3., 3., 4., 4.],
       [1., 1., 2., 2., 3., 3., 4., 4.],
       [5., 5., 7., 7., 8., 8., 9., 9.],
       [5., 5., 7., 7., 8., 8., 9., 9.]], dtype=float32)