In [5]:
import torch
print(torch.cuda.is_available())
print(torch.__version__)

True
1.7.1+cu110


# Tensor
- 텐서란 데이터를 표현하는 단위이다.
## (1) Scalar
- 우리가 알고 있는 상수값이다.
- 하나의 값을 표현할 때 1개의 수치로 표현한 것

In [9]:
scalar1 = torch.tensor([1.])
scalar2 = torch.tensor([3])
print(scalar1)
print(scalar2)

tensor([1.])
tensor([3])


In [15]:
# 스칼라 연산
print("덧셈 : {} + {} = {}".format(scalar1,scalar2,scalar1+scalar2))
print("뺄셈 : {} - {} = {}".format(scalar1,scalar2,scalar1-scalar2))
print("곱셈 : {} * {} = {}".format(scalar1,scalar2,scalar1*scalar2))
print("나누셈 : {} / {} = {}".format(scalar1,scalar2,scalar1/scalar2))

덧셈 : tensor([1.]) + tensor([3]) = tensor([4.])
뺄셈 : tensor([1.]) - tensor([3]) = tensor([-2.])
곱셈 : tensor([1.]) * tensor([3]) = tensor([3.])
나누셈 : tensor([1.]) / tensor([3]) = tensor([0.3333])


In [17]:
# torch에 내장된 연산으로도 가능
print("덧셈 : {} + {} = {}".format(scalar1,scalar2,torch.add(scalar1,scalar2)))
print("뺄셈 : {} - {} = {}".format(scalar1,scalar2,torch.sub(scalar1,scalar2)))
print("곱셈 : {} * {} = {}".format(scalar1,scalar2,torch.mul(scalar1,scalar2)))
print("나누셈 : {} / {} = {}".format(scalar1,scalar2,torch.div(scalar1,scalar2)))

덧셈 : tensor([1.]) + tensor([3]) = tensor([4.])
뺄셈 : tensor([1.]) - tensor([3]) = tensor([-2.])
곱셈 : tensor([1.]) * tensor([3]) = tensor([3.])
나누셈 : tensor([1.]) / tensor([3]) = tensor([0.3333])


## (2) Vectort
- 벡터는 하나의 값을 표현할 때 2개 이상의 수치로 표현한 것이다.
- 스칼라의 형태와 동일한 속성을 갖고 있지만, 여러 수치 값을 이용해 표현하는 방식이다.

In [19]:
vector1 = torch.Tensor([1.,2.,3.])
vector2 = torch.Tensor([3.,4.,5.])
print(vector1)
print(vector2)

tensor([1., 2., 3.])
tensor([3., 4., 5.])


In [20]:
# 벡터 간 사칙연산
print('벡터의 덧셈 : {} + {} = {}'.format(vector1,vector2,vector1+vector2))
print('벡터의 뺄셈 : {} - {} = {}'.format(vector1,vector2,vector1-vector2))
print('벡터의 곱셈 : {} * {} = {}'.format(vector1,vector2,vector1*vector2))
print('벡터의 나누셈 : {} / {} = {}'.format(vector1,vector2,vector1/vector2))

벡터의 덧셈 : tensor([1., 2., 3.]) + tensor([3., 4., 5.]) = tensor([4., 6., 8.])
벡터의 뺄셈 : tensor([1., 2., 3.]) - tensor([3., 4., 5.]) = tensor([-2., -2., -2.])
벡터의 곱셈 : tensor([1., 2., 3.]) * tensor([3., 4., 5.]) = tensor([ 3.,  8., 15.])
벡터의 나누셈 : tensor([1., 2., 3.]) / tensor([3., 4., 5.]) = tensor([0.3333, 0.5000, 0.6000])


In [23]:
# torch 내장함수를 이용한 사칙연산
print('벡터의 덧셈 : {} + {} = {}'.format(vector1,vector2,torch.add(vector1,vector2)))
print('벡터의 뺄셈 : {} - {} = {}'.format(vector1,vector2,torch.sub(vector1,vector2)))
print('벡터의 곱셈 : {} * {} = {}'.format(vector1,vector2,torch.mul(vector1,vector2)))
print('벡터의 나누셈 : {} / {} = {}'.format(vector1,vector2,torch.div(vector1,vector2)))
print('벡터의 내적 : {} dot {} = {}'.format(vector1,vector2,torch.dot(vector1,vector2)))

벡터의 덧셈 : tensor([1., 2., 3.]) + tensor([3., 4., 5.]) = tensor([4., 6., 8.])
벡터의 뺄셈 : tensor([1., 2., 3.]) - tensor([3., 4., 5.]) = tensor([-2., -2., -2.])
벡터의 곱셈 : tensor([1., 2., 3.]) * tensor([3., 4., 5.]) = tensor([ 3.,  8., 15.])
벡터의 나누셈 : tensor([1., 2., 3.]) / tensor([3., 4., 5.]) = tensor([0.3333, 0.5000, 0.6000])
벡터의 내적 : tensor([1., 2., 3.]) dot tensor([3., 4., 5.]) = 26.0


## (3) matrix 행렬
- 행렬은 2개 이상의 벡터값을 통합해 구성된 값으로, 벡터값 간 연산 속도를 빠르게 진행 할 수 있는 선형 대수의 기본 단위이다.

In [31]:
matrix1 = torch.Tensor([[1.,2.],[3.,4.]])
matrix2 = torch.Tensor([[5.,6.],[7.,8.]])
print(matrix1)
print(matrix2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [32]:
# 행렬 간 사칙연산
print("행렬의 덧셈 : {} + {} = {}".format(matrix1,matrix2,matrix1+matrix2))
print("행렬의 뺄셈 : {} - {} = {}".format(matrix1,matrix2,matrix1-matrix2))
print("행렬의 곱셈 : {} * {} = {}".format(matrix1,matrix2,matrix1*matrix2))
print("행렬의 나누셈 : {} / {} = {}".format(matrix1,matrix2,matrix1/matrix2))

행렬의 덧셈 : tensor([[1., 2.],
        [3., 4.]]) + tensor([[5., 6.],
        [7., 8.]]) = tensor([[ 6.,  8.],
        [10., 12.]])
행렬의 뺄셈 : tensor([[1., 2.],
        [3., 4.]]) - tensor([[5., 6.],
        [7., 8.]]) = tensor([[-4., -4.],
        [-4., -4.]])
행렬의 곱셈 : tensor([[1., 2.],
        [3., 4.]]) * tensor([[5., 6.],
        [7., 8.]]) = tensor([[ 5., 12.],
        [21., 32.]])
행렬의 나누셈 : tensor([[1., 2.],
        [3., 4.]]) / tensor([[5., 6.],
        [7., 8.]]) = tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [34]:
# torch 내장함수를 이용한 사칙연산
print("행렬의 덧셈 : {} + {} = {}".format(matrix1,matrix2,torch.add(matrix1,matrix2)))
print("행렬의 뺄셈 : {} - {} = {}".format(matrix1,matrix2,torch.sub(matrix1,matrix2)))
print("행렬의 곱셈 : {} * {} = {}".format(matrix1,matrix2,torch.mul(matrix1,matrix2)))
print("행렬의 나누셈 : {} / {} = {}".format(matrix1,matrix2,torch.div(matrix1,matrix2)))
print("행렬곱 : {} 행렬곱 {} = {}".format(matrix1,matrix2,torch.matmul(matrix1,matrix2)))

행렬의 덧셈 : tensor([[1., 2.],
        [3., 4.]]) + tensor([[5., 6.],
        [7., 8.]]) = tensor([[ 6.,  8.],
        [10., 12.]])
행렬의 뺄셈 : tensor([[1., 2.],
        [3., 4.]]) - tensor([[5., 6.],
        [7., 8.]]) = tensor([[-4., -4.],
        [-4., -4.]])
행렬의 곱셈 : tensor([[1., 2.],
        [3., 4.]]) * tensor([[5., 6.],
        [7., 8.]]) = tensor([[ 5., 12.],
        [21., 32.]])
행렬의 나누셈 : tensor([[1., 2.],
        [3., 4.]]) / tensor([[5., 6.],
        [7., 8.]]) = tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
행렬곱 : tensor([[1., 2.],
        [3., 4.]]) 행렬곱 tensor([[5., 6.],
        [7., 8.]]) = tensor([[19., 22.],
        [43., 50.]])


## (4) 텐서
- 행렬은 2개 이상의 벡터값을 갖는 2차원 배열이라고 표현할 수 있다면, 텐서는 2차원 이상의 배열이라고 표현할 수 있다.

<img src = './images/scalar-vector-matrix-tensor.png'>

In [43]:
tensor1 = torch.Tensor([ [[1.,2.],[3.,4.]] , [[5.,6.],[7.,8.]] ])
tensor2 = torch.Tensor([ [[9.,10.],[11.,12.]] , [[13.,14.],[15.,16.]] ])
print(tensor1)
print(tensor2)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [45]:
# 텐서의 사칙연산
print("텐서의 덧셈 : {} + {} = {}".format(tensor1,tensor2,tensor1+tensor2))
print("텐서의 뺄셈 : {} - {} = {}".format(tensor1,tensor2,tensor1-tensor2))

텐서의 덧셈 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) + tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
텐서의 뺄셈 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) - tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [46]:
print("텐서의 곱셈 : {} * {} = {}".format(tensor1,tensor2,tensor1*tensor2))
print("텐서의 나눗셈 : {} / {} = {}".format(tensor1,tensor2,tensor1/tensor2))

텐서의 곱셈 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) * tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
텐서의 나눗셈 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) / tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [49]:
# torch 내장함수를 이용한 사칙연산
print("텐서의 덧셈 : {} * {} = {}".format(tensor1,tensor2,torch.add(tensor1,tensor2)))
print("텐서의 뺄셈 : {} / {} = {}".format(tensor1,tensor2,torch.sub(tensor1,tensor2)))

텐서의 덧셈 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) * tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])
텐서의 뺄셈 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) / tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [50]:
print("텐서의 곱셈 : {} * {} = {}".format(tensor1,tensor2,torch.mul(tensor1,tensor2)))
print("텐서의 나눗셈 : {} / {} = {}".format(tensor1,tensor2,torch.div(tensor1,tensor2)))

텐서의 곱셈 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) * tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
텐서의 나눗셈 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) / tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [51]:
print("텐서곱 : {} 텐서곱 {} = {}".format(tensor1,tensor2,torch.matmul(tensor1,tensor2)))

텐서곱 : tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) 텐서곱 tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]]) = tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])
