In [2]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import Dataset, DataLoader

In [3]:
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]
device = 'cuda'

In [4]:
class MyDataset(Dataset):
    def __init__(self,x,y):
        self.x = torch.tensor(x).float().to(device)
        self.y = torch.tensor(y).float().to(device)
        
    def __getitem__(self, ix):
        return self.x[ix], self.y[ix]

    def __len__(self):
        return len(x)

In [5]:
ds = MyDataset(x,y)
dl = DataLoader(ds, batch_size=2, shuffle=True)

In [6]:
model = nn.Sequential(
    nn.Linear(2,8),
    nn.ReLU(),
    nn.Linear(8,1)
).to(device)

In [7]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.3324,  0.4780],
                      [-0.0130, -0.4515],
                      [ 0.2238,  0.5498],
                      [-0.5377, -0.6233],
                      [ 0.4306,  0.1370],
                      [ 0.6960, -0.0097],
                      [ 0.1560, -0.3305],
                      [ 0.4496,  0.1853]], device='cuda:0')),
             ('0.bias',
              tensor([ 0.4849, -0.5143,  0.2469, -0.6524,  0.6379,  0.5363,  0.6168, -0.6628],
                     device='cuda:0')),
             ('2.weight',
              tensor([[ 0.0254,  0.3035, -0.0032,  0.1860,  0.3496, -0.0461,  0.2289, -0.3305]],
                     device='cuda:0')),
             ('2.bias', tensor([-0.3039], device='cuda:0'))])

In [8]:
from torchsummary import summary
summary(model,torch.zeros(1,2))

Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 8]                   24
├─ReLU: 1-2                              [-1, 8]                   --
├─Linear: 1-3                            [-1, 1]                   9
Total params: 33
Trainable params: 33
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00


Layer (type:depth-idx)                   Output Shape              Param #
├─Linear: 1-1                            [-1, 8]                   24
├─ReLU: 1-2                              [-1, 8]                   --
├─Linear: 1-3                            [-1, 1]                   9
Total params: 33
Trainable params: 33
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [9]:
loss_func = nn.MSELoss()
from torch.optim import SGD
opt = SGD(model.parameters(), lr = 0.001)

import time
loss_history = []
start = time.time()
for _ in range(50):
    for ix,iy in dl:
        print("ix :{}".format(ix))
        print("iy :{}".format(iy))
        print()
        opt.zero_grad()
        loss_value = loss_func(model(ix),iy)
        loss_value.backward()
        opt.step()
        loss_history.append(loss_value)
    print("-" * 50)
end = time.time()
print(end - start)
        

ix :tensor([[5., 6.],
        [7., 8.]], device='cuda:0')
iy :tensor([[11.],
        [15.]], device='cuda:0')

ix :tensor([[1., 2.],
        [3., 4.]], device='cuda:0')
iy :tensor([[3.],
        [7.]], device='cuda:0')

--------------------------------------------------
ix :tensor([[1., 2.],
        [3., 4.]], device='cuda:0')
iy :tensor([[3.],
        [7.]], device='cuda:0')

ix :tensor([[7., 8.],
        [5., 6.]], device='cuda:0')
iy :tensor([[15.],
        [11.]], device='cuda:0')

--------------------------------------------------
ix :tensor([[1., 2.],
        [5., 6.]], device='cuda:0')
iy :tensor([[ 3.],
        [11.]], device='cuda:0')

ix :tensor([[3., 4.],
        [7., 8.]], device='cuda:0')
iy :tensor([[ 7.],
        [15.]], device='cuda:0')

--------------------------------------------------
ix :tensor([[1., 2.],
        [7., 8.]], device='cuda:0')
iy :tensor([[ 3.],
        [15.]], device='cuda:0')

ix :tensor([[3., 4.],
        [5., 6.]], device='cuda:0')
iy :tensor([[ 7.

In [10]:
val = [[8,9],[10,11],[1.5,2.5]]

In [11]:
model(torch.tensor(val).float().to('cuda'))

tensor([[16.5858],
        [20.3141],
        [ 4.4624]], device='cuda:0', grad_fn=<AddmmBackward>)

In [12]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.4337,  0.5833],
                      [-0.0130, -0.4515],
                      [ 0.3051,  0.6333],
                      [-0.5377, -0.6233],
                      [ 0.6658,  0.3928],
                      [ 0.7439,  0.0377],
                      [ 0.1512, -0.3402],
                      [ 0.3345,  0.0512]], device='cuda:0')),
             ('0.bias',
              tensor([ 0.4889, -0.5143,  0.2491, -0.6524,  0.6585,  0.5358,  0.6120, -0.6818],
                     device='cuda:0')),
             ('2.weight',
              tensor([[ 0.4817,  0.3035,  0.4196,  0.1860,  0.7417,  0.3098,  0.2268, -0.1212]],
                     device='cuda:0')),
             ('2.bias', tensor([-0.2482], device='cuda:0'))])

In [13]:
x

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [14]:
y

[[3], [7], [11], [15]]

In [15]:
torch.save(model.to('cpu').state_dict(), 'mymodel.pth')

In [16]:
model = nn.Sequential(
    nn.Linear(2,8),
    nn.ReLU(),
    nn.Linear(8,1)
).to('cuda')

In [17]:
state_dict = torch.load('mymodel.pth')

In [23]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.4337,  0.5833],
                      [-0.0130, -0.4515],
                      [ 0.3051,  0.6333],
                      [-0.5377, -0.6233],
                      [ 0.6658,  0.3928],
                      [ 0.7439,  0.0377],
                      [ 0.1512, -0.3402],
                      [ 0.3345,  0.0512]], device='cuda:0')),
             ('0.bias',
              tensor([ 0.4889, -0.5143,  0.2491, -0.6524,  0.6585,  0.5358,  0.6120, -0.6818],
                     device='cuda:0')),
             ('2.weight',
              tensor([[ 0.4817,  0.3035,  0.4196,  0.1860,  0.7417,  0.3098,  0.2268, -0.1212]],
                     device='cuda:0')),
             ('2.bias', tensor([-0.2482], device='cuda:0'))])

In [25]:
model.to('cuda')
model(torch.Tensor(val).float().to('cuda'))

tensor([[16.5858],
        [20.3141],
        [ 4.4624]], device='cuda:0', grad_fn=<AddmmBackward>)

In [26]:
x = [[1,2,3,4],[4,5,6,7],[8,9,10,11]]
x = torch.Tensor(x)
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])